In [1]:
import folium
import pandas as pd

In [2]:
df_suburbs = pd.read_excel(r'C:\Users\ebisys\Documents\water_consumption_suburbs.xlsx', index_col=0, sheet_name='Sheet1')
df_suburbs.head(10)

,Suburb,Number of single-residential properties_number,Oct 2017\nkl/month,Month,Year,Latitude,Longitude
0,ATHLONE,2272,11,October,2017,-33.967220,18.502140
1,AURORA,426,10,October,2017,-32.705958,18.485135
2,BANTRY BAY,248,13,October,2017,-33.927953,18.382592
3,BELLVILLE SOUTH,2041,11,October,2017,-33.920011,18.642819
4,BERGVLIET,1488,8,October,2017,-34.047464,18.452499
5,BISHOP LAVIS,3746,9,October,2017,-33.947283,18.575133
6,BISHOPSCOURT,538,12,October,2017,-33.991092,18.444217
7,BLOMTUIN,201,9,October,2017,-33.882677,18.652075
8,BONTEHEUWEL,7098,9,October,2017,-33.950161,18.554446
9,BOTHASIG,3399,9,October,2017,-33.860418,18.544612

In [3]:
df_suburbs.columns

Index(['Suburb', 'Number of single-residential properties_number',
       'Oct 2017\nkl/month', 'Month', 'Year', 'Latitude', 'Longitude'],
      dtype='object')

In [4]:
df_suburbs.shape

(121, 7)

In [5]:
df_suburbs.describe()

,Number of single-residential properties_number,Oct 2017\nkl/month,Year,Latitude,Longitude
count,121.000000,121.000000,121.0,121.000000,121.000000
mean,1849.983471,8.413223,2017.0,-33.944923,18.668673
std,2506.756526,3.275336,0.0,0.217793,0.568946
min,0.000000,0.000000,2017.0,-34.589721,18.329108
25%,364.000000,8.000000,2017.0,-34.037828,18.457490
50%,1009.000000,9.000000,2017.0,-33.950865,18.505041
75%,2411.000000,10.000000,2017.0,-33.908311,18.638249
max,20719.000000,13.000000,2017.0,-32.705958,22.192635

In [6]:
map_osm = folium.Map(location=[-33.925, 18.625], zoom_start=10)

map_osm

In [7]:
map_dark = folium.Map(location=[-33.925, 18.625], tiles='CartoDB dark_matter', zoom_start=10)

map_dark

In [8]:
df_suburbs_location = df_suburbs[['Latitude', 'Longitude']]
#df_suburbs_location
suburbs_location_list = df_suburbs_location.values.tolist()
suburbs_location_list_size = len(suburbs_location_list)
suburbs_location_list_size

121

In [9]:
for point in range(0, suburbs_location_list_size):
    folium.Marker(suburbs_location_list[point]).add_to(map_osm)
    folium.Marker(suburbs_location_list[point]).add_to(map_dark)

map_osm

In [10]:
map_dark

In [11]:
def map_initialization():
    map_osm = folium.Map(location=[-33.925, 18.625], zoom_start=10)
    map_dark = folium.Map(location=[-33.925, 18.625], tiles='CartoDB dark_matter', zoom_start=10)
    return map_osm, map_dark

In [12]:
map_osm, map_dark = map_initialization()

for point in range(0, suburbs_location_list_size):
    folium.Marker(suburbs_location_list[point], popup=df_suburbs['Suburb'][point]).add_to(map_osm)
    folium.Marker(suburbs_location_list[point], popup=df_suburbs['Suburb'][point]).add_to(map_dark)

map_osm

In [13]:
map_dark

In [14]:
map_osm, map_dark = map_initialization()

In [15]:
for point in range(0, suburbs_location_list_size):
    folium.Marker(suburbs_location_list[point], popup=df_suburbs['Suburb'][point], icon=folium.Icon(color='darkblue', icon_color='white', icon='plus', angle=0, prefix='fa')).add_to(map_osm)   
    folium.Marker(suburbs_location_list[point], popup=df_suburbs['Suburb'][point], icon=folium.Icon(color='darkblue', icon_color='white', icon='plus', angle=0, prefix='fa')).add_to(map_dark)

map_osm

In [16]:
map_dark

In [17]:
# Classification
map_osm, map_dark = map_initialization()
for point in range(0, suburbs_location_list_size):
    if df_suburbs['Oct 2017\nkl/month'][point] <= 5:
        folium.Marker(suburbs_location_list[point],
                      popup=df_suburbs['Suburb'][point],
                      icon=folium.Icon(color='green', icon_color='white', icon='thumbs-up', angle=0, prefix='fa')).add_to(map_osm)
        folium.Marker(suburbs_location_list[point],
                      popup=df_suburbs['Suburb'][point],
                      icon=folium.Icon(color='green', icon_color='white', icon='thumbs-up', angle=0, prefix='fa')).add_to(map_dark)

    elif df_suburbs['Oct 2017\nkl/month'][point] > 5 and df_suburbs['Oct 2017\nkl/month'][point] <= 8:
        folium.Marker(suburbs_location_list[point],
                      popup=df_suburbs['Suburb'][point],
                      icon=folium.Icon(color='blue', icon_color='white', icon='thumbs-up', angle=0, prefix='fa')).add_to(map_osm)
        folium.Marker(suburbs_location_list[point],
                      popup=df_suburbs['Suburb'][point],
                      icon=folium.Icon(color='blue', icon_color='white', icon='thumbs-up', angle=0, prefix='fa')).add_to(map_dark)
    
    else:
        folium.Marker(suburbs_location_list[point],
                      popup=df_suburbs['Suburb'][point],
                      icon=folium.Icon(color='red', icon_color='white', icon='thumbs-down', angle=0, prefix='fa')).add_to(map_osm)
        folium.Marker(suburbs_location_list[point],
                      popup=df_suburbs['Suburb'][point],
                      icon=folium.Icon(color='red', icon_color='white', icon='thumbs-down', angle=0, prefix='fa')).add_to(map_dark)
        

map_osm

In [18]:
map_dark

In [19]:
map_points = folium.Map(location=[-33.925, 18.625], tiles='CartoDB dark_matter', zoom_start=10)

for point in range(0, suburbs_location_list_size):
    folium.Circle(
        location=suburbs_location_list[point],
        popup=df_suburbs['Suburb'][point] + ': ' + str(df_suburbs['Oct 2017\nkl/month'][point]) + 'kl',
        radius=str(df_suburbs['Oct 2017\nkl/month'][point] * 100),
        color='#17cbef',
        fill=True,
        opacity=0.8,
        fill_color='#17cbef',
        stroke=True,
        weight=1.0
    ).add_to(map_points)

map_points

In [20]:
# Adding Classification
map_points = folium.Map(location=[-33.925, 18.625], tiles='CartoDB dark_matter', zoom_start=10)

for point in range(0, suburbs_location_list_size):
    # Classify by usage
    if df_suburbs['Oct 2017\nkl/month'][point] <= 8 and df_suburbs['Oct 2017\nkl/month'][point] > 0:
        usage_color = 'green'
    elif df_suburbs['Oct 2017\nkl/month'][point] > 8 and df_suburbs['Oct 2017\nkl/month'][point] <= 10:
        usage_color = '#17cbef'
    elif df_suburbs['Oct 2017\nkl/month'][point] > 10:
        usage_color = 'red'
    else: # Outliers
        usage_color = 'orange'

    folium.Circle(
        location=suburbs_location_list[point],
        popup=df_suburbs['Suburb'][point] + ': ' + str(df_suburbs['Oct 2017\nkl/month'][point]) + 'kl',
        radius=str(df_suburbs['Oct 2017\nkl/month'][point] * 100),
        color=usage_color,
        fill=True,
        opacity=0.8,
        fill_color=usage_color,
        stroke=True,
        weight=1.0
    ).add_to(map_points)

map_points

In [21]:
# Building choropleth map dataset

df_world_countries = pd.read_json(r'C:\Users\ebisys\Documents\world-countries.json')
df_unemployment = pd.read_csv(r'C:\Users\ebisys\Documents\unemployment.csv', skiprows=4, delimiter=',')

df_unemployment.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Unnamed: 63
0,Aruba,ABW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.821000,8.230000,7.936000,8.452000,8.706000,8.864000,8.841000,8.837000,8.808000,NaN
2,Angola,AGO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.863000,7.360000,7.347000,7.331000,7.306000,7.281000,7.724000,8.167000,8.543000,NaN
3,Albania,ALB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,14.200000,13.980000,13.440000,15.640000,17.490000,17.080000,15.220000,13.867000,15.132000,NaN
4,Andorra,AND,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Arab World,ARB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.959137,10.294118,10.431499,10.293865,10.289091,10.266855,10.019851,9.930642,9.808109,NaN
6,United Arab Emirates,ARE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.695000,3.305000,2.971000,2.618000,2.282000,1.933000,1.636000,1.672000,1.710000,NaN
7,Argentina,ARG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.710000,7.180000,7.220000,7.100000,7.270000,7.151000,8.696000,8.518000,8.162000,NaN
8,Armenia,ARM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,19.010000,18.440001,17.309999,16.180000,17.500000,18.260000,18.040001,18.233999,18.275999,NaN
9,American Samoa,ASM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df_unemployment_2018 = df_unemployment[['Country Name', 'Country Code', '2018']]
df_unemployment_2018.head(10)

           Country Name Country Code       2018
0                 Aruba          ABW        NaN
1           Afghanistan          AFG   8.808000
2                Angola          AGO   8.543000
3               Albania          ALB  15.132000
4               Andorra          AND        NaN
5            Arab World          ARB   9.808109
6  United Arab Emirates          ARE   1.710000
7             Argentina          ARG   8.162000
8               Armenia          ARM  18.275999
9        American Samoa          ASM        NaN

In [23]:
# Remove nulls
df_unemployment_2018_clean = df_unemployment_2018.dropna()
df_unemployment_2018_clean.head(10)

            Country Name Country Code       2018
1            Afghanistan          AFG   8.808000
2                 Angola          AGO   8.543000
3                Albania          ALB  15.132000
5             Arab World          ARB   9.808109
6   United Arab Emirates          ARE   1.710000
7              Argentina          ARG   8.162000
8                Armenia          ARM  18.275999
11             Australia          AUS   5.474000
12               Austria          AUT   5.387000
13            Azerbaijan          AZE   5.037000

In [24]:
df_unemployment_2018_clean.shape

(233, 3)

In [25]:
# Prepare data for our map
legendTitle = 'Unemployment rate per country 2018 (%)'

# Data to plot country code and value
data_unemployment = df_unemployment_2018_clean[['Country Code', '2018']]

data_unemployment.head()

  Country Code       2018
1          AFG   8.808000
2          AGO   8.543000
3          ALB  15.132000
5          ARB   9.808109
6          ARE   1.710000

In [26]:
# Create the map
map_unemployment = folium.Map(location=[8.7832, 34.5058], zoom_start=3)

folium.Choropleth(geo_data=r'C:\Users\ebisys\Documents\world-countries.json',
                  data=data_unemployment,
                  columns=['Country Code', '2018'],
                  key_on='feature.id',
                  fill_color='YlOrRd',
                  fill_opacity=0.7,
                  line_opacity=0.2,
                  legend_name=legendTitle
                 ).add_to(map_unemployment)

map_unemployment

In [27]:
# Measuring Boundaries

df_damLevels = pd.read_csv(r'https://raw.githubusercontent.com/EBISYS/Mapping-Dam-Levels/refs/heads/master/DamLevels.txt', delimiter=',')
df_damLevels.head(10)

,Dam,River,Photo,Indicators,FSC,ThisWeek,LastWeek,LastYear
0,Berg River Dam,Berg River,Photo,Indicators,127.1,73.7,75.2,49.9
1,Steenbras-Lower Dam,Steenbras River,Photo,Indicators,33.9,50.2,51.7,35.6
2,Steenbras-Upper Dam,Steenbras River,Photo,Indicators,31.9,70.0,69.8,92.4
3,Theewaterskloof Dam,Riviersonderend River,Photo,Indicators,479.3,40.9,41.9,10.6
4,Voelvlei Dam,Voelvlei River,Photo,Indicators,158.6,65.6,67.5,15.5
5,Wemmershoek Dam,Wemmers River,Photo,Indicators,58.8,61.8,63.5,44.9

In [28]:
df_location = pd.read_csv(r'https://raw.githubusercontent.com/EBISYS/Mapping-Dam-Levels/refs/heads/master/damLocations.txt', delimiter=',')
df_location.head()

                   Dam   Latitude  Longitude
0       Berg River Dam -33.925000  19.060833
1  Steenbras-Upper Dam -34.166300  18.910000
2  Steenbras-Lower Dam -34.179722  18.876389
3  Theewaterskloof Dam -34.078100  19.289200
4         Voelvlei Dam -33.337500  19.033600

In [29]:
# Join the two dataframes on the dam field
df_damData = pd.merge(df_damLevels, df_location, on='Dam', how='left')
df_damData.head()

,Dam,River,Photo,Indicators,FSC,ThisWeek,LastWeek,LastYear,Latitude,Longitude
0,Berg River Dam,Berg River,Photo,Indicators,127.1,73.7,75.2,49.9,-33.925000,19.060833
1,Steenbras-Lower Dam,Steenbras River,Photo,Indicators,33.9,50.2,51.7,35.6,-34.179722,18.876389
2,Steenbras-Upper Dam,Steenbras River,Photo,Indicators,31.9,70.0,69.8,92.4,-34.166300,18.910000
3,Theewaterskloof Dam,Riviersonderend River,Photo,Indicators,479.3,40.9,41.9,10.6,-34.078100,19.289200
4,Voelvlei Dam,Voelvlei River,Photo,Indicators,158.6,65.6,67.5,15.5,-33.337500,19.033600

In [30]:
# Prepare data to plot
df_dam_locations = df_damData[['Latitude', 'Longitude']]
dam_location_list = df_dam_locations.values.tolist()
dam_location_list_size = len(dam_location_list)
dam_location_list_size

6

In [31]:
map_dams = folium.Map(location=[-33.925, 18.625], zoom_start=10)
for point in range(0, dam_location_list_size):
    folium.Marker(dam_location_list[point], popup=df_damData['Dam'][point]).add_to(map_dams)

map_dams

In [32]:
map_url = folium.Map(location=[-34.078100, 19.289200],
                     tiles='http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
                     zoom_start=12,
                     attr='Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community')

for point in range(0, dam_location_list_size):
    folium.Marker(dam_location_list[point], popup=df_damData['Dam'][point]).add_to(map_url)

map_url

In [33]:
from folium.plugins import MeasureControl

map_url.add_child(MeasureControl())

map_url

In [34]:
# Add Layer Control
map_layers = map_points

add = '/MapServer/tile/{z}/{y}/{x}'
ESRI = dict(World_Ocean_Base='http://services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Base',
            World_Navigation_Charts='http://services.arcgisonline.com/ArcGIS/rest/services/Specialty/World_Navigation_Charts',
            NatGeo_World_Map='http://services.arcgisonline.com/arcgis/rest/services/NatGeo_World_Map/MapServer',
            World_Imagery='http://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer',
            World_Physical_Map='http://services.arcgisonline.com/arcgis/rest/services/World_Physical_Map/MapServer',
            World_Shaded_Relief='http://services.arcgisonline.com/arcgis/rest/services/World_Shaded_Relief/MapServer',
            World_Street_Map='http://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer',
            World_Terrain_Base='http://services.arcgisonline.com/arcgis/rest/services/World_Terrain_Base/MapServer',
            World_Topo_Map='http://services.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer')

for tile_name, tile_url in ESRI.items():
    tile_url += add
    folium.TileLayer(tile_url,
                    name=tile_name,
                    attr='Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community').add_to(map_points)

folium.LayerControl().add_to(map_layers)

map_layers

In [37]:
# Creating Heat Map
from folium.plugins import HeatMap

# Create our point map object
map_heat = folium.Map(location=[-33.925, 18.625], tiles='CartoDB dark_matter', zoom_start=10)

for point in range(0, suburbs_location_list_size):
    folium.Circle(
        location=suburbs_location_list[point],
        popup=df_suburbs['Suburb'][point] + ': ' + str(df_suburbs['Oct 2017\nkl/month'][point]) + ' kl',
        radius=15,
        color='#17cbef',
        fill=True,
        opacity=0.8,
        fill_color='#17cbef',
        stroke=True,
        weight=1.0
    ).add_to(map_heat)

# Convert to array format for our heatmap
suburbsArray = df_suburbs[['Latitude', 'Longitude']].values

# plot heatmap
map_heat.add_child(HeatMap(suburbsArray))

map_heat

In [35]:
heat = 'map_heat.html'
unemployment = 'map_unemployment.html'

def export_maps(map_file, map_obj):
    map_obj.save(map_file)

In [39]:
export_maps(unemployment, map_unemployment)